### ISSUE TITLE
Resources metadata doesn't work

### ISSUE THREAD

**Issue by davorg** [davorg/calendar-simple#3]
According to MetaCPAN (https://metacpan.org/dist/Calendar-Simple) the repo and issue metadata is missing. But it's there in Build.PL (https://metacpan.org/release/DAVECROSS/Calendar-Simple-v2.0.1/source/Build.PL)

**Comment by choroba** [comment]
That's really weird, as I don't see any relevant difference to another distribution of yours, [Array::Compare](https://metacpan.org/pod/Array::Compare). The Build.PL seems to have exactly the same structure, Makefile.PL is laconic in the same way. The `META.json` files are different, though: [A:C's one](https://metacpan.org/release/DAVECROSS/Array-Compare-v3.0.8/source/META.json) contains the repository and bugtracker entries, while the [C:S's one](https://metacpan.org/release/DAVECROSS/Calendar-Simple-v2.0.1/source/META.json) doesn't. When I run `Build dist` in a fresh checkout of the repository, the created tar.gz contains the information, unlike the one in CPAN.

**Comment by davorg** [comment]
Hmm... rerunning `Build dist` in a newly-created container gives the correct behaviour. So I guess I just bump the version number and re-release it. I wonder if it was a bug in the version of Module::Build I was previously using.

Thanks for looking.

**Comment by davorg** [comment]
Yep. Fixed in 2.0.2.

https://metacpan.org/release/DAVECROSS/Calendar-Simple-v2.0.2
